from ExampleScriptAAA import *
from ExampleScriptBBB import *
from ExampleScriptCCC import *
from ExampleScriptDDD import *
ZTHE,ZWORD,ZDEEP_LEARNING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZPREDICTIVE_MODELING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZNAMING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZTHINKING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZCROSSCOMPILING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZHYPERTHREADING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZBECOMING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZRESONATING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZVIBRATING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZCOMPREHENDING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZINTERRUPTING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZBEARING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZWANTING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZLONGING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZYEARNING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZWISHING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZHELPING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZINSPIRING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZACCOMPLISHING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZRESULTING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZOCCURRING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZACHIEVING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZCOMPLETING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZSUCCEEDING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZSERVING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZGETTING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZAVOIDING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZSUFFERING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZUNASSUMING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZHEALING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZREFRESHING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZPREVENTING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZRENEWING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZOFFERING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZPLEASING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZAPPEALING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZINTERESTING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZSATISFYING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZQUALIFYING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZDENOTING,ZIS,ZFUTURE_TENSE
ZTHE,ZWORD,ZDIFFERING,ZIS,ZFUTURE_TENSE
