from ExampleScriptAAA import *
from ExampleScriptBBB import *
from ExampleScriptCCC import *
from ExampleScriptDDD import *
ZTHE,ZWORD,ZLAN,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZGAMEWORLD,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZLOCALSPACE,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZLOCALLOCATION,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZLOCALPARAMETER,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZPLACE2,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZPRIVATEPUBLICLOCATION,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZPERSONALPUBLICLOCATION,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZPRIVATEPERSONALLOCALLOCATION,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZNETWORKPARAMETER,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZDOMAINLOCATION,ZIS,ZAN,ZPLACE2
