class Language_Extension_008_2:
    EXTROVERTED_SENSATIONS = "IS ONE OF THE FOUR PERSONALITY FUNCTIONS"
    EXTRAVERTED_INTUITION = "IS ONE OF THE FOUR PERSONALITY FUNCTIONS"
    INTROVERTED_SENSING = "IS ONE OF THE FOUR PERSONALITY FUNCTIONS"
    INTROVERTED_INTUITION = "IS ONE OF THE FOUR PERSONALITY"
    INTROVERTED_THINKING = "IS ONE OF THE FOUR PERSONALITY FUNCTIONS" 
    EXTRAVERTED_THINKING = "IS ONE OF THE FOUR PERSONALITY FUNCTIONS"
    INTROVERTED_FEELING = "IS ONE OF THE FOUR PERSONALITY FUNCTIONS"
    EXTRAVERTED_FEELING = "IS ONE OF THE FOUR PERSONALITY FUNCTIONS"
