from ExampleScriptAAA import *
from ExampleScriptBBB import *
from ExampleScriptCCC import *
from ExampleScriptDDD import *
ZTHE,ZWORD,ZCREATOR,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZMAGE,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZMAGI,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZMAGICALL,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZMAGIKALL,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZKID,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZCHILD,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZWOMAN,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZMAN,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZBOY,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZGIRL,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZMAGE2,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZPERSON,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZMULTIPLICATIONATOR,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZMULTIPLICATOR,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZPROGRAMMER,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZLEADER,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZTIM,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZTAYLOR,ZIS,ZAN,ZPERSON
ZTHE,ZWORD,ZZACK,ZIS,ZAN,ZPERSON