from ExampleScriptAAA import *
from ExampleScriptBBB import *
from ExampleScriptCCC import *
ZTHE,ZWORD,ZDOMAIN,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZPLACE,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZREALITY,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZREALM,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZLOCATION,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZLOOPHOLE,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZLOOPHOLE2,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZLOOPHOLE3,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZLOOPHOLE4,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZFIELD,ZIS,ZAN,ZPLACE2
ZTHE,ZWORD,ZPHYSICAL2,ZIS,ZAN,ZPLACE2
