from pyclbr import Class
from ExampleScriptAAA import *
from ExampleScriptBBB import *
from ExampleScriptCCC import *
from ExampleScriptDDD import *
from ExampleScriptEEE import *
from FUTURE_TENSEGRAMMAR import *
from PAST_TENSEGRAMMAR import *
from SINGULARGRAMMAR import *
from PLURALGRAMMAR import *
from eXPERIMENT002 import *
from PERSONGRAMMAR import *
from PLACEGRAMMAR import *
from THINGGRAMMAR import *
from IDEAGRAMMAR import *
from EXTENSIONONENOUNSANDVERBSGRAMMAR import *
from EXTENSIONONEPERSONGRAMMAR import *
from EXTENSIONONEPLACEGRAMMAR import *
from EXTENSIONONETHINGGRAMMAR import *
from EXTENSIONONEIDEAGRAMMAR import *
from EXTENSIONONESINGULARGRAMMAR import *
from EXTENSIONONEPLURALGRAMMAR import *
from Numbers_One_To_OneThousand import *
from COLORS import *
from Pokemonarrayscript import *
from Creature_Stats import *
from CreatureConditions import *


ZTHE,ZFOLLOWING,ZDATA2,ZIS,"POKEMON",ZDATA2
class POKEMONTERMS:
    ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
    ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
    ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
    ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
    ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
    ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
    ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
    ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
    ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
    ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
    ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
    ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
    ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
    ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
    ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
    ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
    ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
    ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
    ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
    ZPOKEMON_STATS = ZMORE,ZTHAN,ZONE,ZPOKEMON_STAT

class POKEMONTERMS_2:
    class POKEMONTERMS:
        ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
        ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
        ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
        ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
        ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
        ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
        ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
        ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
        ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
        ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
        ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
        ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
        ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
        ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
        ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
        ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
        ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
        ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
        ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE

    ZSTATUS_CONDITION = ZIS,ZA,ZCONDITION,ZTHAT,ZAFFECTS,ZTHE,ZABILITY,ZTO,POKEMONTERMS.ZBATTLE,ZFOR,ZA,"POKEMON"
    ZLEVELUPMETHOD = ZIS,ZA,ZPROCESS,ZOF,ZUSING,ZA,ZSPECIFIC,ZMETHOD,ZFOR,ZGETTING,ZEXPERIENCE,ZFROM,ZA,ZSPECIFIC,ZSOURCE,ZTO,ZINCREASE,ZTHE,ZLEVEL
    ZLEVELUPMETHODS = ZMORE,ZTHAN,ZONE,ZLEVELUPMETHOD
    ZLEVELUP = ZTHE,ZPROCESS,ZTO,ZGAIN,ZEXPERIENCE,ZFROM,ZNORMAL,ZLEVELUPMETHODS
    ZMOVE_TUTOR = ZIS,ZA,ZCHARACTER,ZWHO,ZCAN,ZALLOW,ZA,"POKEMON",ZTO,ZLEARN,ZA,ZATTACK,ZTHAT,ZCANNOT,ZBE,ZLEARNED,ZWITH,ZLEVELUP

class IVSANDEVS:
    class POKEMONTERMS:
        ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
        ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
        ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
        ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
        ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
        ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
        ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
        ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
        ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
        ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
        ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
        ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
        ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
        ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
        ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
        ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
        ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
        ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
        ZPOKEMON_STATS = ZMORE,ZTHAN,ZONE,ZPOKEMON_STAT


    class POKEMONTERMS_2:
        class POKEMONTERMS:
            ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
            ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
            ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
            ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
            ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
            ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
            ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
            ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
            ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
            ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
            ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
            ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
            ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
            ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
            ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
            ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
            ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
            ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
            ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
    ZSTATUS_CONDITION = ZIS,ZA,ZCONDITION,ZTHAT,ZAFFECTS,ZTHE,ZABILITY,ZTO,POKEMONTERMS.ZBATTLE,ZFOR,ZA,"POKEMON"
    ZLEVELUPMETHOD = ZIS,ZA,ZPROCESS,ZOF,ZUSING,ZA,ZSPECIFIC,ZMETHOD,ZFOR,ZGETTING,ZEXPERIENCE,ZFROM,ZA,ZSPECIFIC,ZSOURCE,ZTO,ZINCREASE,ZTHE,ZLEVEL
    ZLEVELUPMETHODS = ZMORE,ZTHAN,ZONE,ZLEVELUPMETHOD
    ZLEVELUP = ZTHE,ZPROCESS,ZTO,ZGAIN,ZEXPERIENCE,ZFROM,ZNORMAL,ZLEVELUPMETHODS
    ZMOVE_TUTOR = ZIS,ZA,ZCHARACTER,ZWHO,ZCAN,ZALLOW,ZA,"POKEMON",ZTO,ZLEARN,ZA,ZATTACK,ZTHAT,ZCANNOT,ZBE,ZLEARNED,ZWITH,ZLEVELUP

    INDIVIDUAL_VALUES_AND_EFFORT_VALUES = ZARE,ZTWO,ZHIDDEN,POKEMONTERMS.ZPOKEMON_STATS,ZTHAT,ZCAN,ZBE,ZUSED,ZTO,ZIMPROVE,ZTHE,ZCAPABILITIES,ZOF,ZA,"POKEMON"
    IV = ZIS,ZA,POKEMONTERMS.ZPOKEMON_STAT,ZTHAT,ZIS,ZDETERMINED,ZWHEN,ZA,"POKEMON",ZIS,ZOBTAINED,ZAND,ZOR,ZCREATED
    EV = ZIS,ZA,POKEMONTERMS.ZPOKEMON_STAT,ZTHAT,ZCAN,ZBE,ZINCREASED,ZBY,ZA,POKEMONTERMS.ZBATTLE,ZWITH,ZSPECIFIC,"POKEMON"
    IVS = ZMORE,ZTHAN,ZONE,IV
    ZEVS = ZMORE,ZTHAN,ZONE,EV

class EVADE:
    ZEVADE = ZIS,ZTO,ZAVOID

class POKEMONBREEDING:
    BREEDING = ZIS,ZA,ZFEATURE,ZTHAT,ZALLOWS,ZTHE,ZPLAYER,ZTO,ZCREATE,ZNEW,"POKEMON",ZBY,ZCOMBINING,ZTWO,"POKEMON",ZOF,ZTHE,ZSAME,ZSPECIES
    EGG_GROUPS = ZIS,ZA,ZCLASSIFIED,ZSYSTEM,ZUSED,ZTO,ZDETERMINE,ZWHICH,"POKEMON",ZCAN,ZBREED,ZWITH,ZOTHER,"POKEMON"

class POKEMONCHARACTERISTIC:
    CHARACTERISTIC = ZIS,ZA,ZSMALL,ZDESCRIPTION,ZTHAT,ZCAN,ZAPPEAR,ZON,ZTHE,ZSUMMARY,ZSCREEN,ZAND,ZDETERMINES,ZTHE,IVSANDEVS.INDIVIDUAL_VALUES_AND_EFFORT_VALUES

class POKEMONNATURE:
    ZNATURE = ZIS,ZA,ZCHARACTERISTIC,ZOF,ZA,"POKEMON",ZTHAT,ZCAN,ZINFLUENCE,ZHOW,ZITS,POKEMONTERMS.ZPOKEMON_STATS,ZINCREASE

class POKEMONSTATS:
    #HITPOINTS = ZARE,ZWHAT,ZDETERMINE,ZHOW,ZMUCH,ZDAMAGE,ZA,"POKEMON",ZCAN,ZENDURE,ZBEFORE,ZFAINTING
    SPECIALATTACK = ZIS,ZWHAT,ZDETERMINES,ZTHE,ZATTRIBUTE,ZOF,ZA,ZATTACK,ZFROM,ZA,"POKEMON",ZAND,ZIS,ZUSED,ZTO,ZCALCULATE,ZATTACKS,

class POKEMONHABITAT_DEX:
    HABITAT_DEX = ZIS,ZA,ZLIST,ZOF,ZALL,"POKEMON",ZTHAT,ZCAN,ZBE,ZFOUND,ZWITHIN,ZEACH,ZAREA,ZTHAT,ZEXISTS

class POKEMONABILITY:
    class POKEMONTERMS:
        ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
        ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
        ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
        ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
        ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
        ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
        ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
        ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
        ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
        ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
        ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
        ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
        ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
        ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
        ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
        ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
        ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
        ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
        ZPOKEMON_STATS = ZMORE,ZTHAN,ZONE,ZPOKEMON_STAT


    class POKEMONTERMS_2:
        class POKEMONTERMS:
            ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
            ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
            ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
            ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
            ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
            ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
            ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
            ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
            ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
            ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
            ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
            ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
            ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
            ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
            ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
            ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
            ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
            ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
            ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
    ZSTATUS_CONDITION = ZIS,ZA,ZCONDITION,ZTHAT,ZAFFECTS,ZTHE,ZABILITY,ZTO,POKEMONTERMS.ZBATTLE,ZFOR,ZA,"POKEMON"
    ZLEVELUPMETHOD = ZIS,ZA,ZPROCESS,ZOF,ZUSING,ZA,ZSPECIFIC,ZMETHOD,ZFOR,ZGETTING,ZEXPERIENCE,ZFROM,ZA,ZSPECIFIC,ZSOURCE,ZTO,ZINCREASE,ZTHE,ZLEVEL
    ZLEVELUPMETHODS = ZMORE,ZTHAN,ZONE,ZLEVELUPMETHOD
    ZLEVELUP = ZTHE,ZPROCESS,ZTO,ZGAIN,ZEXPERIENCE,ZFROM,ZNORMAL,ZLEVELUPMETHODS
    ZMOVE_TUTOR = ZIS,ZA,ZCHARACTER,ZWHO,ZCAN,ZALLOW,ZA,"POKEMON",ZTO,ZLEARN,ZA,ZATTACK,ZTHAT,ZCANNOT,ZBE,ZLEARNED,ZWITH,ZLEVELUP

    ABILITY = ZIS,ZPASSIVE,ZEFFECTS,ZTHAT,"POKEMON",ZCAN,ZHAVE,ZIN,POKEMONTERMS.ZBATTLE
class POKEMONISFICTIONAL:
    class POKEMONTERMS:
        ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
        ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
        ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
        ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
        ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
        ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
        ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
        ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
        ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
        ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
        ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
        ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
        ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES,ZINCLUDING
        ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
        ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
        ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
        ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
        ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
        ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
        ZA,"POKEMON",ZCAN,ZINCREASE,ZAFFECTION,ZBY,ZPETTING_THE_POKEMON
    ZA,"POKEMON",ZIS,ZA,POKEMONTERMS.ZCREATURE,ZMADE,ZFROM,ZFICTION

class POKEMONAFFECTIONINFORMATION:
    class POKEMONTERMS_2:
        class POKEMONTERMS:
            ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
            ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
            ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
            ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
            ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
            ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
            ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
            ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
            ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
            ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
            ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
            ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
            ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
            ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
            ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
            ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
            ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
            ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
            ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
    class EVADE:
        ZEVADE = ZIS,ZTO,ZAVOID

    ZSTATUS_CONDITION = ZIS,ZA,ZCONDITION,ZTHAT,ZAFFECTS,ZTHE,ZABILITY,ZTO,POKEMONTERMS.ZBATTLE,ZFOR,ZA,"POKEMON"
    ZLEVELUPMETHOD = ZIS,ZA,ZPROCESS,ZOF,ZUSING,ZA,ZSPECIFIC,ZMETHOD,ZFOR,ZGETTING,ZEXPERIENCE,ZFROM,ZA,ZSPECIFIC,ZSOURCE,ZTO,ZINCREASE,ZTHE,ZLEVEL
    ZLEVELUPMETHODS = ZMORE,ZTHAN,ZONE,ZLEVELUPMETHOD
    ZLEVELUP = ZTHE,ZPROCESS,ZTO,ZGAIN,ZEXPERIENCE,ZFROM,ZNORMAL,ZLEVELUPMETHODS
    ZMOVE_TUTOR = ZIS,ZA,ZCHARACTER,ZWHO,ZCAN,ZALLOW,ZA,"POKEMON",ZTO,ZLEARN,ZA,ZATTACK,ZTHAT,ZCANNOT,ZBE,ZLEARNED,ZWITH,ZLEVELUP
    ZA,"POKEMON",ZWITH,ZA,ZLARGE,ZAFFECTION,ZRATE,ZHAS,ZA,ZINCREASED,ZCHANCE,ZTO,EVADE.ZEVADE,ZATTACKS
    ZA,"POKEMON",ZWITH,ZA,ZLARGE,ZAFFECTION,ZRATE,ZHAS,ZA,ZINCREASED,ZCHANCE,ZOF,ZACHIEVING,ZA,ZHIGHER,CREATURECRITICALCHANCE
    ZA,"POKEMON",ZWITH,ZA,ZLARGE,ZAFFECTION,ZRATE,ZHAS,ZTHE,ZABILITY,ZTO,ZAVOID,ZBECOMING,ZAFFECTED,ZBY,ZA,ZSTATUS_CONDITION
   
class POKEMONAFFECTIONINFORMATION_2:
    class POKEMONTERMS:
        ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
        ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
        ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
        ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
        ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
        ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
        ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
        ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
        ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
        ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
        ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
        ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
        ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES,ZINCLUDING
        ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
        ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
        ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
        ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
        ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
        ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
        ZA,"POKEMON",ZCAN,ZINCREASE,ZAFFECTION,ZBY,ZPETTING_THE_POKEMON
        #ZA,"POKEMON",ZCAN,ZINCREASE,ZAFFECTION,ZBY,ZGIVING,ZTHE,"POKEMON",ZFOOD
        #ZA,"POKEMON",ZCAN,ZINCREASE,ZAFFECTION,ZBY,ZPLAYING,ZWITH,ZTHE,"POKEMON"
        #ZA,"POKEMON",ZCAN,ZINCREASE,ZAFFECTION,ZBY,ZWINNING,ZBATTLES,ZWITH,ZTHE,"POKEMON"
        #ZA,"POKEMON",ZCAN,ZINCREASE,ZAFFECTION,ZBY,ZUSING,ZA,ZPOFFIN
class QUESTIONS:
    class POKEMONTERMS:
        ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
        ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
        ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
        ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
        ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
        ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
        ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
        ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
        ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
        ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
        ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
        ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
        ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
        ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
        ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
        ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
        ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
        ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
        ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
    #ASKS IF THE POKEMON CAN FLY OUTSIDE OF BATTLE TO A NEW LOCATION
    class FLYOUTSIDEOFBATTLE:
        ZCAN,"POKEMON",ZUSE,FLY,ZOUTSIDE,ZOF,POKEMONTERMS.ZBATTLE
    #ASKS IF THE POKEMON CAN SURF OUTSIDE OF BATTLE
    class SURFOUTSIDEOFBATTLE:
        ZCAN,"POKEMON",ZUSE,SURF,ZOUTSIDE,ZOF,POKEMONTERMS.ZBATTLE
    #POKEMON COULD BE ASLEEP OR PARALYZED AND CANT MOVE
    class CANATTACK:
        ZCAN,"POKEMON",ZATTACK
    #POKEMON COULD BE OUT OF POWER POINTS OR
    class CANUSEANATTACK:
        ZCAN,"POKEMON",ZUSE,ZAN,ZATTACK
    #ASKS IF THE CREATURE CAN BATTLE AND
    class CANBATTLE:
        ZCAN,"POKEMON",POKEMONTERMS.ZBATTLE

class POKEMONSTATEMENTS:
    ZTHE,"POKEMON",ZCANNOT,ZATTACK
    ZDO,ZNOT,ZALLOW,"POKEMON",ZTO,ZATTACK
    ZTHE,"POKEMON",ZCAN,ZUSE,ZTHE,ZOBJECT3
    ZCANNOT,ZUSE,ZOBJECT3,ZON,"POKEMON"
    ZTHE,"POKEMON",ZCANNOT,POKEMONTERMS.ZBATTLE
    ZTHE,"POKEMON",ZIS,ZNOT,ZHOLDING,ZAN,ZOBJECT3
   
class ISITABLETOBEFOUNDATTHISROUTE:
    #ASKS IF THE CREATURE CAN BE FOUND AT ROUTE 211
    ZIS,"POKEMON",ZABLE,ZTO,ZBE,ZFOUND,ZAT,ZROUTE,TWOHUNDREDELEVEN
    ZIS,"POKEMON",ZABLE,ZTO,ZBE,ZFOUND,ZAT,ZROUTE,TWOHUNDREDTWELVE
    ZIS,"POKEMON",ZABLE,ZTO,ZBE,ZFOUND,ZAT,ZROUTE,TWOHUNDREDTHIRTEEN
    ZIS,"POKEMON",ZABLE,ZTO,ZBE,ZFOUND,ZAT,ZROUTE,TWOHUNDREDFOURTEEN
    ZIS,"POKEMON",ZABLE,ZTO,ZBE,ZFOUND,ZAT,ZROUTE,TWOHUNDREDFIFTEEN
    ZIS,"POKEMON",ZABLE,ZTO,ZBE,ZFOUND,ZAT,ZROUTE,TWOHUNDREDSIXTEEN
    ZIS,"POKEMON",ZABLE,ZTO,ZBE,ZFOUND,ZAT,ZROUTE,TWOHUNDREDSEVENTEEN

class POKEDEXNUMBER:
    class BULBASAURDEXENTRY:
        BULBASAUR,ZIS,ZCONSIDERED,"POKEMON",ONE,ZINSIDE,ZTHE,"POKEDEX"
    class IVYSAURDEXENTRY:
        IVYSAUR,ZIS,ZCONSIDERED,"POKEMON",TWO,ZINSIDE,ZTHE,"POKEDEX"
    class VENUSAURDEXENTRY
        VENUSAUR,ZIS,ZCONSIDERED,"POKEMON",THREE,ZINSIDE,ZTHE,"POKEDEX"

class RESPONSE:
    ZONLY,ZIF,"GYM_BADGE",ZFROM,"CELADON CITY",ZHAS,ZBEEN,ZOBTAINED

class BLANKISAPOKEMON:
    MAGMAR,ZIS,ZA,"POKEMON"
   

class TECHNICAL_MACHINE_DATA:
        class POKEMONTERMS:
        ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
        ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
        ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
        ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
        ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
        ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
        ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
        ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
        ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
        ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
        ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
        ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
        ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES,
        ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
        ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
        ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
        ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
        ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
        ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
    class TECHNICAL_MACHINE_DATA2:
        TECHNICAL_MACHINE = ZIS,ZAN,ZOBJECT3,ZTHAT,ZCAN,ZBE,ZUSED,ZTO,ZALLOW,ZA,POKEMONTERMS.ZCREATURE,ZTO,ZLEARN,ZA,ZNEW,ZATTACK
    FIREPUNCH,ZIS,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,ZTHAT,ZA,ZCOMPATIBLE,POKEMONTERMS.ZCREATURE,ZCAN,ZLEARN

class TECHNICAL_MACHINE_DATA2:
    TECHNICAL_MACHINE = ZIS,ZAN,ZOBJECT3,ZTHAT,ZCAN,ZBE,ZUSED,ZTO,ZALLOW,ZA,POKEMONTERMS.ZCREATURE,ZTO,ZLEARN,ZA,ZNEW,ZATTACK
    ZA,TECHNICAL_MACHINE,ZCAN,ZONLY,ZBE,ZUSED,ZWITHIN,ZA,POKEMONTERMS.ZBATTLE
    ZTHERE,ZIS,ZMORE,ZTHAN,ZONE,TECHNICAL_MACHINE

class HIDDEN_MACHINE_DATA2:
    class POKEMONTERMS:
        ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
        ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
        ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
        ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
        ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
        ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
        ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
        ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
        ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
        ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
        ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
        ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
        ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
        ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
        ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
        ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
        ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
        ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
        ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
    class POKEMONTERMS_2:
        class POKEMONTERMS:
            ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
            ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
            ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
            ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
            ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
            ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
            ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
            ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
            ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
            ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
            ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
            ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
            ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
            ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
            ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
            ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
            ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
            ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
            ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
    ZSTATUS_CONDITION = ZIS,ZA,ZCONDITION,ZTHAT,ZAFFECTS,ZTHE,ZABILITY,ZTO,POKEMONTERMS.ZBATTLE,ZFOR,ZA,"POKEMON"
    ZLEVELUPMETHOD = ZIS,ZA,ZPROCESS,ZOF,ZUSING,ZA,ZSPECIFIC,ZMETHOD,ZFOR,ZGETTING,ZEXPERIENCE,ZFROM,ZA,ZSPECIFIC,ZSOURCE,ZTO,ZINCREASE,ZTHE,ZLEVEL
    ZLEVELUPMETHODS = ZMORE,ZTHAN,ZONE,ZLEVELUPMETHOD
    ZLEVELUP = ZTHE,ZPROCESS,ZTO,ZGAIN,ZEXPERIENCE,ZFROM,ZNORMAL,ZLEVELUPMETHODS
    ZMOVE_TUTOR = ZIS,ZA,ZCHARACTER,ZWHO,ZCAN,ZALLOW,ZA,"POKEMON",ZTO,ZLEARN,ZA,ZATTACK,ZTHAT,ZCANNOT,ZBE,ZLEARNED,ZWITH,ZLEVELUP

    HIDDEN_MACHINE = ZIS,ZAN,ZOBJECT3,ZTHAT,ZCAN,ZBE,ZUSED,ZTO,ZALLOW,ZA,POKEMONTERMS.ZCREATURE,ZTO,ZLEARN,ZA,ZNEW,ZATTACK
    ZA,HIDDEN_MACHINE,ZA,ZCAN,ZBE,ZUSED,ZOUTSIDE,ZOF,POKEMONTERMS.ZBATTLE
    ZA,HIDDEN_MACHINE,ZCANNOT,ZBE,ZREMOVED,ZREMOVED,ZWITHOUT,ZA,ZMOVE_TUTOR

class POKEMON_TYPES:
    TYPE = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    TYPE[0] = "FIRE"
    TYPE[1] = "WATER"
    TYPE[2] = "ELECTRIC"
    TYPE[3] = "GROUND"
    TYPE[4] = "ROCK"
    TYPE[5] = "FLYING"
    TYPE[6] = "GRASS"
    TYPE[7] = "BUG"
    TYPE[8] = "POISON"
    TYPE[9] = "STEEL"
    TYPE[10] = "DARK"
    TYPE[11] = "PSYCHIC"
    TYPE[12] = "ICE"
    TYPE[13] = "DRAGON"
    TYPE[14] = "NORMAL"
    TYPE[15] = "FIGHTING"
    TYPE[16] = "GHOST"

class MOVETYPE:
    class MOVETYPE_FIREPUNCH:
        FIREPUNCH,ZIS,ZAN,POKEMON_TYPES.TYPE[0],ZTYPE,ZATTACK
    class MOVETYPE_THUNDERPUNCH:
        THUNDERPUNCH,ZIS,ZAN,POKEMON_TYPES.TYPE[12],ZTYPE,ZATTACK
    class MOVETYPE_ICEPUNCH:
        ICEPUNCH,ZIS,ZAN,POKEMON_TYPES.TYPE[2],ZTYPE,ZATTACK
    class MOVETYPE_MEGAPUNCH:
        MEGAPUNCH,ZIS,ZAN,POKEMON_TYPES.TYPE[14],ZTYPE,ZATTACK

class MOVEDATA:
    class DEFINEDMOVETERMS:
        PHYSICAL_ATTACK = ZIS,ZA,ZATTACK,ZTHAT,ZSENDS,ZDAMAGE,ZFROM,ZTHE,ATTACKSTAT
        MOVE_POWER_POINTS = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMANY,ZUSES,ZA,ZATTACK,ZCAN,ZHAVE,ZBEFORE,ZIT,ZNEEDS,ZTO,ZBE,ZRESTORED,ZTO,ZUSE,ZAGAIN
        MOVE_POWER = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMUCH,ZDAMAGE,ZA,ZATTACK,ZSHALL,ZDO,ZTO,ZA,"POKEMON"
   
    class FIREPUNCHDATA:
        class DEFINEDMOVETERMS:
            PHYSICAL_ATTACK = ZIS,ZA,ZATTACK,ZTHAT,ZSENDS,ZDAMAGE,ZFROM,ZTHE,ATTACKSTAT
            MOVE_POWER_POINTS = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMANY,ZUSES,ZA,ZATTACK,ZCAN,ZHAVE,ZBEFORE,ZIT,ZNEEDS,ZTO,ZBE,ZRESTORED,ZTO,ZUSE,ZAGAIN
            MOVE_POWER = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMUCH,ZDAMAGE,ZA,ZATTACK,ZSHALL,ZDO,ZTO,ZA,"POKEMON"
        FIREPUNCH,ZIS,ZAN,ZATTACK
        ZTHE,ZATTACK,FIREPUNCH,ZHAS,SEVENTYFIVE,DEFINEDMOVETERMS.MOVE_POWER
        ZTHE,ZATTACK,FIREPUNCH,ZHAS,FIFTEEN,DEFINEDMOVETERMS.MOVE_POWER_POINTS
        ZTHE,ZDESCRIPTION,ZFOR,ZTHE,ZATTACK,FIREPUNCH,ZIS,'THE USER GATHERS A FLAME AROUND THEIR FIST AND ATTACKS THE FOE WITH A STRONG PUNCH'
        ZTHE,ZATTACK,ZEFFECT,ZDESCRIPTION,ZFOR,FIREPUNCH,ZIS,ZTHE,ZATTACK,FIREPUNCH,ZHAS,ZA,TWENTY,ZPERCENT,ZTO,"BURN",ZTHE,"POKEMON",
        ZTHE,ZATTACK,FIREPUNCH,ZIS,ZA,DEFINEDMOVETERMS.PHYSICAL_ATTACK
    class THUNDERPUNCHDATA:
        class DEFINEDMOVETERMS:
            PHYSICAL_ATTACK = ZIS,ZA,ZATTACK,ZTHAT,ZSENDS,ZDAMAGE,ZFROM,ZTHE,ATTACKSTAT
            MOVE_POWER_POINTS = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMANY,ZUSES,ZA,ZATTACK,ZCAN,ZHAVE,ZBEFORE,ZIT,ZNEEDS,ZTO,ZBE,ZRESTORED,ZTO,ZUSE,ZAGAIN
            MOVE_POWER = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMUCH,ZDAMAGE,ZA,ZATTACK,ZSHALL,ZDO,ZTO,ZA,"POKEMON"
        THUNDERPUNCH,ZIS,ZAN,ZATTACK
        ZTHE,ZATTACK,THUNDERPUNCH,ZHAS,SEVENTYFIVE,DEFINEDMOVETERMS.MOVE_POWER
        ZTHE,ZATTACK,THUNDERPUNCH,ZHAS,FIFTEEN,DEFINEDMOVETERMS.MOVE_POWER_POINTS
        ZTHE,ZDESCRIPTION,ZFOR,ZTHE,ZATTACK,THUNDERPUNCH,ZIS,'THE USER GATHERS LIGHTNING AROUND ITS FIST AND ATTACKS THE FOE WITH A STRONG PUNCH'
        ZTHE,ZATTACK,ZEFFECT,ZDESCRIPTION,ZFOR,THUNDERPUNCH,ZIS,ZTHE,ZATTACK,THUNDERPUNCH,ZHAS,ZA,TWENTY,ZPERCENT,ZTO,"PARALYZE",ZTHE,"POKEMON"
        ZTHE,ZATTACK,THUNDERPUNCH,ZIS,ZA,DEFINEDMOVETERMS.PHYSICAL_ATTACK
    class ICEPUNCHDATA:
        class DEFINEDMOVETERMS:
            PHYSICAL_ATTACK = ZIS,ZA,ZATTACK,ZTHAT,ZSENDS,ZDAMAGE,ZFROM,ZTHE,ATTACKSTAT
            MOVE_POWER_POINTS = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMANY,ZUSES,ZA,ZATTACK,ZCAN,ZHAVE,ZBEFORE,ZIT,ZNEEDS,ZTO,ZBE,ZRESTORED,ZTO,ZUSE,ZAGAIN
            MOVE_POWER = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMUCH,ZDAMAGE,ZA,ZATTACK,ZSHALL,ZDO,ZTO,ZA,"POKEMON"
        ICEPUNCH,ZIS,ZAN,ZATTACK
        ZTHE,ZATTACK,ICEPUNCH,ZHAS,SEVENTYFIVE,DEFINEDMOVETERMS.MOVE_POWER
        ZTHE,ZATTACK,ICEPUNCH,ZHAS,FIFTEEN,DEFINEDMOVETERMS.MOVE_POWER_POINTS
        ZTHE,ZDESCRIPTION,ZFOR,ZTHE,ZATTACK,ICEPUNCH,ZIS,'THE USER GATHERS COLD AIR TO FORM ICE AROUND ITS FIST AND ATTACKS THE FOE WITH A STRONG PUNCH'
        ZTHE,ZATTACK,ZEFFECT,ZDESCRIPTION,ZFOR,ICEPUNCH,ZIS,ZTHE,ZATTACK,ICEPUNCH,ZHAS,ZA,TWENTY,ZPERCENT,ZTO,"PARALYZE",ZTHE,"POKEMON"
        ZTHE,ZATTACK,ICEPUNCH,ZIS,ZA,DEFINEDMOVETERMS.PHYSICAL_ATTACK
    class MEGAPUNCHDATA:
        class DEFINEDMOVETERMS:
            PHYSICAL_ATTACK = ZIS,ZA,ZATTACK,ZTHAT,ZSENDS,ZDAMAGE,ZFROM,ZTHE,ATTACKSTAT
            MOVE_POWER_POINTS = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMANY,ZUSES,ZA,ZATTACK,ZCAN,ZHAVE,ZBEFORE,ZIT,ZNEEDS,ZTO,ZBE,ZRESTORED,ZTO,ZUSE,ZAGAIN
            MOVE_POWER = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMUCH,ZDAMAGE,ZA,ZATTACK,ZSHALL,ZDO,ZTO,ZA,"POKEMON"
        MEGAPUNCH,ZIS,ZAN,ZATTACK
        ZTHE,ZATTACK,MEGAPUNCH,ZHAS,EIGHTY,DEFINEDMOVETERMS.MOVE_POWER
        ZTHE,ZATTACK,MEGAPUNCH,ZHAS,TEN,DEFINEDMOVETERMS.MOVE_POWER_POINTS
        ZTHE,ZDESCRIPTION,ZFOR,ZTHE,ZATTACK,MEGAPUNCH,ZIS,'THE USER GATHERS ENOUGH ENERGY TO THROW A FORCEFUL PUNCH WITH GREAT STRENGTH AND ATTACKS THE FOE WITH A STRONG FORCE'
        ZTHE,ZATTACK,ZEFFECT,ZDESCRIPTION,ZFOR,MEGAPUNCH,ZDOES,ZNOT,ZEXIST
        ZTHE,ZATTACK,MEGAPUNCH,ZIS,ZA,DEFINEDMOVETERMS.PHYSICAL_ATTACK
    class BULLETPUNCHDATA:
        class DEFINEDMOVETERMS:
            PHYSICAL_ATTACK = ZIS,ZA,ZATTACK,ZTHAT,ZSENDS,ZDAMAGE,ZFROM,ZTHE,ATTACKSTAT
            MOVE_POWER_POINTS = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMANY,ZUSES,ZA,ZATTACK,ZCAN,ZHAVE,ZBEFORE,ZIT,ZNEEDS,ZTO,ZBE,ZRESTORED,ZTO,ZUSE,ZAGAIN
            MOVE_POWER = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMUCH,ZDAMAGE,ZA,ZATTACK,ZSHALL,ZDO,ZTO,ZA,"POKEMON"
        BULLETPUNCH,ZIS,ZAN,ZATTACK
        ZTHE,ZATTACK,BULLETPUNCH,ZHAS,FORTY,DEFINEDMOVETERMS.MOVE_POWER
        ZTHE,ZATTACK,BULLETPUNCH,ZHAS,THIRTY,DEFINEDMOVETERMS.MOVE_POWER_POINTS
        ZTHE,ZDESCRIPTION,ZFOR,ZTHE,ZATTACK,BULLETPUNCH,ZIS,'THE USER STRIKES THE FOE WITH FAST FIERCE PUNCHES IN MULTIPLE SUCESSES TO MAKE ONE SEQUENTIAL STRIKE'
        ZTHE,ZATTACK,ZEFFECT,ZDESCRIPTION,ZFOR,BULLETPUNCH,ZIS,ZTHAT,ZTHERE,ZIS,ZA,ZGEAR,ZONE,ZPRIORITY,ZFOR,ZTHE,ZATTACK
        ZTHE,ZATTACK,BULLETPUNCH,ZIS,ZA,DEFINEDMOVETERMS.PHYSICAL_ATTACK
    class MACHPUNCHDATA:
        class DEFINEDMOVETERMS:
            PHYSICAL_ATTACK = ZIS,ZA,ZATTACK,ZTHAT,ZSENDS,ZDAMAGE,ZFROM,ZTHE,ATTACKSTAT
            MOVE_POWER_POINTS = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMANY,ZUSES,ZA,ZATTACK,ZCAN,ZHAVE,ZBEFORE,ZIT,ZNEEDS,ZTO,ZBE,ZRESTORED,ZTO,ZUSE,ZAGAIN
            MOVE_POWER = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMUCH,ZDAMAGE,ZA,ZATTACK,ZSHALL,ZDO,ZTO,ZA,"POKEMON"
        MACHPUNCH,ZIS,ZAN,ZATTACK
        ZTHE,ZATTACK,MACHPUNCH,ZHAS,FORTY,DEFINEDMOVETERMS.MOVE_POWER
        ZTHE,ZATTACK,MACHPUNCH,ZHAS,THIRTY,DEFINEDMOVETERMS.MOVE_POWER_POINTS
        ZTHE,ZDESCRIPTION,ZFOR,ZTHE,ZATTACK,MACHPUNCH,ZIS,'A FIERCE RAPID PUNCH IS MADE AT THE FOE AT MACH SPEED'
        ZTHE,ZATTACK,ZEFFECT,ZDESCRIPTION,ZFOR,MACHPUNCH,ZIS,ZTHAT,ZTHERE,ZIS,ZA,ZGEAR,ZONE,ZPRIORITY,ZFOR,ZTHE,ZATTACK
        ZTHE,ZATTACK,MACHPUNCH,ZIS,ZA,DEFINEDMOVETERMS.PHYSICAL_ATTACK
    class DIZZYPUNCHDATA:
        class DEFINEDMOVETERMS:
            PHYSICAL_ATTACK = ZIS,ZA,ZATTACK,ZTHAT,ZSENDS,ZDAMAGE,ZFROM,ZTHE,ATTACKSTAT
            MOVE_POWER_POINTS = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMANY,ZUSES,ZA,ZATTACK,ZCAN,ZHAVE,ZBEFORE,ZIT,ZNEEDS,ZTO,ZBE,ZRESTORED,ZTO,ZUSE,ZAGAIN
            MOVE_POWER = ZIS,ZTHE,ZMEASURE,ZOF,ZHOW,ZMUCH,ZDAMAGE,ZA,ZATTACK,ZSHALL,ZDO,ZTO,ZA,"POKEMON"
        DIZZYPUNCH,ZIS,ZAN,ZATTACK
        ZTHE,ZATTACK,DIZZYPUNCH,ZHAS,FORTY,DEFINEDMOVETERMS.MOVE_POWER
        ZTHE,ZATTACK,DIZZYPUNCH,ZHAS,THIRTY,DEFINEDMOVETERMS.MOVE_POWER_POINTS
        ZTHE,ZDESCRIPTION,ZFOR,ZTHE,ZATTACK,DIZZYPUNCH,ZIS,'A HEAVYWEIGHT PUNCH THAT WHEN IT HITS THERE IS A CHANCE TO CONFUSE THE FOE'
        ZTHE,ZATTACK,ZEFFECT,ZDESCRIPTION,ZFOR,DIZZYPUNCH,ZIS,ZTHAT,ZTHERE,ZIS,ZA,TWENTY,ZPERCENT,ZCHANCE,ZTO,CONFUSE,ZTHE,ZTARGET,ZUPON,ZSUCCESSFUL,ZATTACK
        ZTHE,ZATTACK,DIZZYPUNCH,ZIS,ZA,DEFINEDMOVETERMS.PHYSICAL_ATTACK

class POKEMONTHATCANLEARNFIREPUNCH_BYLEVELUP:
    MAGBY,ZCAN,ZLEARN,FIREPUNCH,ZAT,ZLEVEL,TWENTYEIGHT
    MAGMAR,ZCAN,ZLEARN,FIREPUNCH,ZAT,ZLEVEL,TWENTYEIGHT
    MAGMORTAR,ZCAN,ZLEARN,FIREPUNCH,ZAT,ZLEVEL,TWENTYEIGHT

class POKEMONTHATCANLEARNFIREPUNCH_BYTM:
    class POKEMONTERMS:
        ZCOMPETITIVE = ZADEPT,ZAT,ZCHALLENGING,ZSOMEONE,ZOR,ZSOMETHING
        ZCOMPETING = ZCHALLENGING,ZEACH,ZOTHER
        ZPOKEBALL = ZIS,ZA,ZDEVICE,ZUSED,ZTO,ZGAIN,ZCONTROL,ZOF,ZAND,ZSTORE,ZA,"POKEMON",ZWITHIN,ZTHE,ZDEVICE,ZITSELF
        ZCOMPETITION = ZIS,ZA,ZTERM,ZTO,ZDESCRIBE,ZTHE,ZCOMPETITIVE,ZRELATION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE
        ZRIVALRY = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZGROUPS
        ZCONTEST = ZIS,ZA,ZCOMPETITION,ZBETWEEN,ZTWO,ZOR,ZMORE,ZPEOPLE,ZOR,ZBY,ZTEAM,ZOF,ZPEOPLE,ZCOMPETING,ZOR,ZWITH,ZANOTHER,ZTEAM
        ZTRAIN_POKEMON = ZIS,ZTHE,ZPROCESS,ZOF,ZDEVELOPING,ZTHE,ZSKILLS,ZAND,ZABILITIES,ZAND,ZCAPABILITIES,ZOF,ZA,"POKEMON"
        ZAFFECTIONATE = ZIS,ZTHE,ZFEELING,ZOF,ZAFFECTION,ZTOWARDS,ZSOMETHING
        ZCAPTURE = ZTO,ZGAIN,ZCONTROL,ZOF,ZUSING,ZAN,ZOBJECT3
        ZCATCH = ZCAPTURE,ZAND,ZSTORE,ZWITHIN,ZA,ZCONTAINER
        ZCREATURE = ZIS,ZA,ZLIVING,ZBEING
        ZCATCH_POKEMON = ZTO,ZCATCH,"POKEMON",ZUSING,ZA,ZTYPE,ZOF,ZPOKEBALL
        ZPOKEMON_TRAINER = ZIS,ZA,ZPERSON,ZWHO,ZCAN,ZCATCH_POKEMON,ZAND,ZTRAIN_POKEMON,ZAND,ZUSE,ZTHEM,ZFOR,ZMANY,ZCIRCUMSTANCES
        ZBATTLE = ZIS,ZA,ZCONTEST,ZBETWEEN,ZA,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZAND,ZANOTHER,ZINDIVIDUAL,ZPOKEMON_TRAINER,ZIN,ZWHICH,ZTHEY,ZUSE,ZTHEIR,"POKEMON",ZTO,ZATTACK,ZEACH,ZOTHER
        ZPETTING_THE_POKEMON = ZIS,ZAN,ZACTION,ZTHAT,ZA,ZPOKEMON_TRAINER,ZCAN,ZPERFORM,ZTO,ZSHOW,ZAFFECTION,ZFOR,ZTHEIR,"POKEMON"
        ZPOKEMON_TRAINERS = ZMORE,ZTHAN,ZONE,ZPOKEMON_TRAINER
        ZPOKEMON_STAT = ZIS,ZA,ZNUMBER,ZVALUE,ZTHAT,ZDETERMINES,ZTHE,ZCAPABILITIES,ZAND,ZACTIONS,ZOF,ZA,"POKEMON",ZWHILE,ZWITHIN,ZBATTLE
        ZAFFECTION = ZIS,ZA,ZPOKEMON_STAT,ZTHAT,ZMEASURES,ZHOW,ZMUCH,ZAFFECTIONATE,ZA,"POKEMON",ZIS,ZTO,ZITS,ZPOKEMON_TRAINER
        ZPOKEMON_BATTLES = ZMORE,ZTHAN,ZONE,ZBATTLE
    class TECHNICAL_MACHINE_DATA2:
        TECHNICAL_MACHINE = ZIS,ZAN,ZOBJECT3,ZTHAT,ZCAN,ZBE,ZUSED,ZTO,ZALLOW,ZA,POKEMONTERMS.ZCREATURE,ZTO,ZLEARN,ZA,ZNEW,ZATTACK
   
class MOVEDATAFORTECHNICHALMACHINES:
    class TECHNICALMACHINESKNOWN:
        FIREPUNCH,ZIS,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        THUNDERPUNCH,ZIS,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        ICEPUNCH,ZIS,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        MEGAPUNCH,ZIS,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        BULLETPUNCH,ZIS,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        MACHPUNCH,ZIS,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        DIZZYPUNCH,ZIS,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
    #FIRE PUNCH
    class SPECIFICDATAFORTECHNICALMACHINEFIREPUNCH:
        #FIREPUNCH TM - CAN LEARN THE TECHNICAL MACHINE FIREPUNCH
        MAGBY,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        MAGMAR,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        MAGMORTAR,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        HITMONCHAN,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        CHARMANDER,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        CHARMELEON,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        CHARIZARD,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        SNORLAX,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        CHIMCHAR,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        MONFERNO,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        INFERNAPE,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        COMBUSKEN,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
        INFERNAPE,ZCAN,ZLEARN,ZTHE,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE,FIREPUNCH
    class SPECIFICDATAFORFIREPUNCH:
        #FIREPUNCH TM - CAN LEARN FIREPUNCH FROM A TECHNICAL MACHINE
        MAGBY,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        MAGMAR,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        MAGMORTAR,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        HITMONCHAN,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        CHARMANDER,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        CHARMELEON,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        CHARIZARD,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        SNORLAX,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        CHIMCHAR,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        MONFERNO,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        INFERNAPE,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        COMBUSKEN,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE
        INFERNAPE,ZCAN,ZLEARN,FIREPUNCH,ZFROM,ZA,TECHNICAL_MACHINE_DATA2.TECHNICAL_MACHINE

class ATTACKSTATDATA:
    BULBASAUR,ZHAS,ZAN,ATTACKSTAT,ZOF,THIRTYTWO

class DEFENSESTATDATA:
    BULBASAUR,ZHAS,ZAN,DEFENSESTAT,ZOF,FIFTYEIGHT

class SPECIALATTACKSTATDATA:
    BULBASAUR,ZHAS,ZA,SPECIALATTACKSTAT,ZOF,SIXTYFOUR

class SPECIALDEFENSESTATDATA:

